### ISSUE TITLE
How to generate assets for firebase deployment

### ISSUE THREAD

**Issue by kevmunui** [alex996/react-exercises#10]
Hi Alex, 
Thanks for the tutorials, I love them so much. Quick question when getting the production build we only have the main.js and main.js.map. No index or bundle files. How do we generate assets what we can deploy to say firebase for this such app?
regards!

**Comment by kevmunui** [comment]
For reference this is the build script I'm talking about  and here is the final dist after building
`"build": "rm -rf dist public && webpack --mode production --progress"`
<img width="253" alt="Screen Shot 2020-10-22 at 6 53 03 PM" src="https://user-images.githubusercontent.com/10658722/96947426-02d48a00-1498-11eb-96d1-fa07e3bed709.png">

**Comment by alex996** [comment]
@kevmunui Thanks for your question. If you are deploying a single-page app, you could use [`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin) to generate `index.html`. Here's an [example in this repo](https://github.com/alex996/react-exercises/blob/master/webpack.config.js#L14). If you'd like to pre-render the site i.e. generate HTML pages for each route (for example, if SEO is critical), I'd suggest [`react-snap`](https://github.com/stereobooster/react-snap).

**Comment by alex996** [comment]
Let me know if this was helpful.
