### ISSUE TITLE
 Error: Cannot find module 'react-jss/lib/jss'

### ISSUE THREAD

**Issue by asbaghel** [alex996/react-exercises#2]
I downloaded the final branch but it throws an error

**Comment by alex996** [comment]
Thanks for reporting. Are you referring to `ssr/final` branch? I've just updated dependencies and migrated to MUI v4 on all branches. Should be working fine now, although you'll see some breaking changes (e.g. `ThemeProvider` instead of `JssProvider`). Let me know if it works
