### ISSUE TITLE
ssr/final client styles not loaded

### ISSUE THREAD

**Issue by daalgi** [alex996/react-exercises#3]
The server side render shows the page as expected. But when the client bundle is fully loaded the styling defined within each react component is lost: 
- Header button flex.
- Exercises Paper margin, padding, height.

**Comment by alex996** [comment]
Not sure I'm understanding the issue. Are you referring to `ssr/final` branch? I just booted the server, and the UI seems to load just fine. There is no flicker on page reload on my end.

**Comment by daalgi** [comment]
Yeah, I was referring to `ssr/final` branch. I followed your tutorial on youtube and I had this issue of losing the styles defined in each component. Then I tried to clone the branch of the repo, but I still had the same problem. Here are the screenshots that show the UI before and after main.js is loaded.

![ssr00](https://user-images.githubusercontent.com/14979844/74101305-9f3c4380-4b38-11ea-9709-b982d4fe6dd6.PNG)
![ssr01](https://user-images.githubusercontent.com/14979844/74101307-a2373400-4b38-11ea-9d9b-6542a36e9a16.PNG)

**Comment by alex996** [comment]
Can you share the commands that you're running?

**Comment by daalgi** [comment]
`git clone -b ssr/final --single-branch https://github.com/alex996/react-exercises.git`
`cd react-exercises`
`yarn`
`yarn webpack --mode production --progress`
`node dist/main`

**Comment by alex996** [comment]
Exactly what I suspected. You're building a prod bundle, so you need to start the server in prod mode. Run `NODE_ENV=production node dist/main` instead.

**Comment by alex996** [comment]
If not, just use the NPM scripts in the repo: `npm run build` and `npm start`.

**Comment by daalgi** [comment]
That was it! Thanks! Since I'm using Windows, I had to change a bit the 'start' command:
`yarn webpack --mode production --progress`
`set NODE_ENV=production&&node dist/main`

**Comment by alex996** [comment]
Awesome!
