### ISSUE TITLE
Onchange events not firing

### ISSUE THREAD

**Issue by kevmunui** [alex996/react-exercises#8]
Hi Alex!
(Big fan here!)
I've been learning react using some of your tutorials then stumbled onto this bug. I cloned your repo on my local, ran all the scripts to initialize the app

1. yarn
2. yarn build:dev

And even yarn watch after this but I can not get the `onchange callbacks` to fire in the material UI components to fire
Have you seen this before?

**Comment by alex996** [comment]
You are referring to `ssr/final` branch, is that right? I bumped the deps and tweaked the webpack config a bit, but other than that, it seems to be working. By the way, the scripts are mutually exclusive: `build` for prod, `build:dev` for a one-time dev build, and `watch` for a continuous dev build. Thanks for opening the issue.

**Comment by kevmunui** [comment]
I just pulled from your fixes and it works like a charm, do you know what could have cause that bug I'm just curious?
